CREATE TABLE `candidateregistration` (
  `id` VARCHAR(191) NOT NULL,
  `fullName` VARCHAR(191) NOT NULL,
  `gender` VARCHAR(191) NOT NULL,
  `dateOfBirth` DATETIME(3) NULL,
  `major` VARCHAR(191) NOT NULL,
  `className` VARCHAR(191) NOT NULL,
  `studentId` VARCHAR(191) NOT NULL,
  `placeOfBirth` VARCHAR(191) NOT NULL,
  `identityNumber` VARCHAR(191) NOT NULL,
  `identityIssuedDate` DATETIME(3) NULL,
  `identityIssuedPlace` VARCHAR(191) NOT NULL,
  `address` TEXT NOT NULL,
  `phone` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `facebookUrl` VARCHAR(191) NULL,
  `talent` TEXT NULL,
  `selfIntroduction` TEXT NULL,
  `inspirationalMessage` TEXT NULL,
  `facultyIntroduction` TEXT NULL,
  `ambassadorPlan` TEXT NULL,
  `portraitImageUrl` VARCHAR(191) NOT NULL,
  `fullBodyImageUrl` VARCHAR(191) NOT NULL,
  `heightCm` DECIMAL(5,2) NULL,
  `weightKg` DECIMAL(5,2) NULL,
  `measurementBust` DECIMAL(5,2) NULL,
  `measurementWaist` DECIMAL(5,2) NULL,
  `measurementHip` DECIMAL(5,2) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `adminNote` TEXT NULL,
  `consentAccepted` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `candidateregistration_status_createdAt_idx` (`status`, `createdAt`),
  INDEX `candidateregistration_email_idx` (`email`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
